name: Deploy
on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build step
        run: "deno task build"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "world-chat"
          entrypoint: "main.ts"
          root: "."
    env:
      ALCHEMY_API_SEPOLIA: ${{ secrets.ALCHEMY_API_SEPOLIA }}
      ALCHEMY_API_MAINNET: ${{ secrets.ALCHEMY_API_MAINNET }}
      BLOCKSCOUT_APIKEY: ${{ secrets.BLOCKSCOUT_APIKEY }}
      WORLD_CHAT_ADDRESS_SEPOLIA: ${{ secrets.WORLD_CHAT_ADDRESS_SEPOLIA }}
      WORLD_CHAT_ADDRESS_MAINNET: ${{ secrets.WORLD_CHAT_ADDRESS_MAINNET }}
      WC_RELAYER_KEY: ${{ secrets.WC_RELAYER_KEY }}
          
